### ISSUE TITLE
rename modules ?

### ISSUE THREAD

**Issue by denisri** [neurospin/point-cloud-pattern-mining#4]
The python modules do not match at all the project title, "Point cloud pattern mining" as opposed to "moving_averages". The project used to be named "moving_averages" but has changed. Things should probably move along inside also. In setup.py (which I propose to split to use an info.py in #3) the project and package names are still "moving_averages" and should be changed.
We can move python code to a renamed module, and let the old `moving_averages` fake it in order to keep compatibility for a while. `point-colud-pattern-mining`, of course, cannot make a good python module name, because 1) it contains "-" characters, and 2) it is too long. I can propose "`pcpm`" (although it already exists several times on github, but not on pipy, thus would be a valid pip module name).

**Comment by mpascucci** [comment]
solved in the text commit, thanks!
